build:
  cuda_version: "12.1.1"
  system_packages:
    - "libxext6"
    - "libgl1-mesa-glx"
  python_packages:
    - "git+https://github.com/huggingface/diffusers.git@refs/pull/5895/head"
    - "torch==2.0.1"
